port 26381

bind 0.0.0.0

protected-mode no

sentinel resolve-hostnames yes

sentinel announce-hostnames yes

sentinel monitor todo-primary redis-primary 6379 2

sentinel down-after-milliseconds todo-primary 5000

sentinel failover-timeout todo-primary 15000

sentinel parallel-syncs todo-primary 1